name: Validate JSON Schemas
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches:
      - master
env:
  CVE_SCHEMA_DIR: schema/v5.0
  CVE_SCHEMA_FILENAME: CVE_JSON_5.0.schema
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NPM dependencies (i.e., ajv)
        run: |
          sudo npm install --loglevel verbose -g yargs ajv-formats@"^1.5.x" ajv-cli@"^4.0.x"
      # Rename the schema, since AJV doesn't like non-".json" extensions
      - name: Rename schema for AJV
        run: |
          sed 's/file\://g' "${CVE_SCHEMA_DIR}/${CVE_SCHEMA_FILENAME}" > "${CVE_SCHEMA_DIR}/cve-schema.json"
      - name: Validate JSON schema
        run: |
          ajv compile -c ajv-formats -s "${CVE_SCHEMA_DIR}/cve-schema.json"
